### ISSUE TITLE
Any analysis results to be reported for the paper?

### ISSUE THREAD

**Issue by abhishektiwari** [dtkerns/d2#7]
Are there any analysis results reported by the paper as stated in summary section _Our results show that the SB should be taken seriously as a candidate for creating DSAs._. I can't find any benchmark or analysis to support the statement in paper or repository.  

[For JOSS Review](https://github.com/openjournals/joss-reviews/issues/6825)

**Comment by dtkerns** [comment]
The original version of this paper (paper/full_paper.md) had many of the details you are asking for. However, the initial (pre)reviewers asked me to trim the paper down significantly for submission to JOSS.

**Comment by abhishektiwari** [comment]
Thanks. Much appreciated. Can analysis results be uploaded to Zenodo and referenced in paper? We can ask editors.

**Comment by dtkerns** [comment]
I'm not familiar with Zenodo, but it sounds like a reasonable request.

**Comment by dtkerns** [comment]
Sorry for the delay. After consulting with my advisor, we came to the the conclusion that an appendix right here would be more appropriate. I've added the file `paper/appendix.md` to address this issue.

**Comment by dtkerns** [comment]
Anything else for me to do before I close this?

**Comment by abhishektiwari** [comment]
Thanks. I am closing this.
