### ISSUE TITLE
[JOSS Review] Automated examples to run on every commit as E2E test

### ISSUE THREAD

**Issue by abhishektiwari** [dtkerns/d2#8]
Given there are no automated test for this package, I strongly recommend authors adding a Github action which will run the `app1` and `app2` in `example` folder on eery commit. 

See [JOSS testing](https://joss.readthedocs.io/en/latest/review_criteria.html#tests) requirements.

> Good: An automated test suite hooked up to continuous integration (GitHub Actions, Circle CI, or similar)
OK: Documented manual steps that can be followed to objectively check the expected functionality of the software (e.g., a sample input file to assert behavior)
Bad (not acceptable): No way for you, the reviewer, to objectively assess whether the software works

[JOSS Review](https://github.com/openjournals/joss-reviews/issues/6825)

**Comment by dtkerns** [comment]
There is a "human in the loop" portion of the script, but I think I can automate it with a few assumptions. I'll get that added ASAP.

**Comment by dtkerns** [comment]
As a first step, I've added a `test` target in the example directory Makefile. That should get me to "OK" ... in the coming days (as time allows) I will attempt to automate it to full blown CI/CD.

**Comment by dtkerns** [comment]
I'm a CI/CD noob, can I get an assist with the yaml?

**Comment by abhishektiwari** [comment]
Let me have look later in the day into your YAML.

**Comment by abhishektiwari** [comment]
Nice
