### ISSUE TITLE
Improve single phrase in step-by-step and mention appendix

### ISSUE THREAD

**Issue by manuel-g-castro** [dtkerns/d2#9]
Hello, @dtkerns:

I really appreciate having a for dummies (like me) step by step for reproducing our software. I found a little issue at the end of line 10 and begining of 11 of `step-by-step.md`. Where you write "build a `.ll` file insted also ...". Maybe you meant to say that `.o` and also `.ll`  files will be build. But I am unsure.

I also like a lot your `appendix.md`, which is really nicely writen and interesting. Maybe it is worth it to mention the existance of this file on the `readme.md`?

**Comment by dtkerns** [comment]
it actually does not build a `.o` file ... from the `clang` man page:
```
-emit-llvm
              Generate output files in LLVM formats, suitable for link time optimization.  When used  with  -S  this
              generates  LLVM intermediate language assembly files...
the flags `-S -emit-llvm` cause the `clang` compiler to only do the the "first" step of converting the C into `clang`'s intermediate

**Comment by dtkerns** [comment]
the appendix.md was part of the original paper. unfortunately, it caused the paper to exceed the length of the JOSS guidelines. but one of the reviewers specifically asked to see (quantitative) results, so I added it back as an appendix.

I'm open to suggestions on a good way to refer to it in the readme.

**Comment by manuel-g-castro** [comment]
> it actually does not build a `.o` file ... from the `clang` man page:
> 
> ```
> -emit-llvm
>               Generate output files in LLVM formats, suitable for link time optimization.  When used  with  -S  this
>               generates  LLVM intermediate language assembly files...
> ```
> 
> so we stop short of generating the `.o` files with those flags.

So there is an extra `also` there on the test. Cool! Solved.

> the appendix.md was part of the original paper. unfortunately, it caused the paper to exceed the length of the JOSS guidelines. but one of the reviewers specifically asked to see (quantitative) results, so I added it back as an appendix.
> 
> I'm open to suggestions on a good way to refer to it in the readme.

Hi! Maybe include an example section? Or performance benchmark... I am unsure about what works best, but feels a pity to have it there but you have to dig the repository to find it.

**Comment by dtkerns** [comment]
how's this wording?

# Benchmarks

To meet JOSS length guidelines, the quantitative analysis was removed from the paper, but is available as an appendix. see paper/appendix.md

**Comment by dtkerns** [comment]
perhaps too passive aggressive?

**Comment by dtkerns** [comment]
Quantitative analysis is available as an appendix. see paper/appendix.md

**Comment by tosiron** [comment]
No need to include "to meet Joss length guidelines".



Tosi

________________________________
From: dtkerns ***@***.***>
Sent: Tuesday, August 27, 2024 6:36 AM
To: dtkerns/d2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT] Re: [dtkerns/d2] Improve single phrase in step-by-step and mention appendix (Issue #9)


External Email

________________________________
how's this wording?

Benchmarks

To meet JOSS length guidelines, the quantitative analysis was removed from the paper, but is available as an appendix. see paper/appendix.md

**Comment by manuel-g-castro** [comment]
Okay, perfect! Thanks, all!
